project: 
  type: website
  output-dir: docs

website:
  title: "Data Analysis Portfolio: Kai Chen"
  navbar:
    left:
      - text: "About Me"
        href: ./aboutme.html
      - text: "Projects"
        menu:
          - text: "R Coding Exercise"
            href: ./coding_exercise.html
          - text: "Visualization Exercise"
            href: ./visualization_exercise.html
          - text: "Tidy Tuesday Exercise"
            href: ./tidytuesday_exercise.html
          - text: "Module 4: Data Analysis Exercise (Week of 1/30)"
            href: ./dataanalysis_exercise.html
      - text: "Flu Analysis"
        menu: 
          - text: "Wrangling"
            href: ./fluanalysis/code/wrangling.html
          - text: "Exploration"
            href: ./fluanalysis/code/exploration.html
          - text: "Fitting"
            href: ./fluanalysis/code/fitting.html
          - text: "Model Evaluation"
            href: ./fluanalysis/code/modeleval.html
    right:
      - icon: github 
        href: https://github.com/Kamidala/kaichen-MADA-portfolio        

format:
  html:
    theme: pulse
    highlight: zenburn
    css: styles.css
    toc: FALSE


